#!/bin/bash
# ECC Project Auto-Detector
# Detects project tech stack and generates dynamic skill loading instructions
# Called at session start to auto-load relevant skills

PROJECT_DIR="${1:-$PWD}"
OUTPUT_FILE="${2:-/tmp/ecc-skill-load.md}"

# Verify directory exists
if [ ! -d "$PROJECT_DIR" ]; then
    echo "❌ ERROR: Directory '$PROJECT_DIR' not found"
    echo "SKILLS_TO_LOAD:"
    echo "  - coding-standards"
    exit 1
fi

detect_file() {
    [ -f "$PROJECT_DIR/$1" ] && echo "yes" || echo "no"
}

SKILLS_NEEDED=()
LANGUAGES=()
FRAMEWORKS=()

# --- Language Detection ---
if [ "$(detect_file "package.json")" = "yes" ]; then
    LANGUAGES+=("TypeScript" "JavaScript")
    SKILLS_NEEDED+=("coding-standards")
    SKILLS_NEEDED+=("git-workflow")
    SKILLS_NEEDED+=("error-handling")
    SKILLS_NEEDED+=("security-review")
    
    # Check for specific frameworks
    if grep -q '"react"' "$PROJECT_DIR/package.json" 2>/dev/null || [ -f "$PROJECT_DIR/tsconfig.json" ]; then
        if [ -d "$PROJECT_DIR/src/app" ] || [ -d "$PROJECT_DIR/pages" ]; then
            SKILLS_NEEDED+=("nextjs-turbopack")
        fi
        SKILLS_NEEDED+=("react-patterns")
        SKILLS_NEEDED+=("react-testing")
        SKILLS_NEEDED+=("react-performance")
    fi
    
    if grep -q '"vue"' "$PROJECT_DIR/package.json" 2>/dev/null || [ -f "$PROJECT_DIR/nuxt.config.ts" ]; then
        SKILLS_NEEDED+=("vue-patterns")
        SKILLS_NEEDED+=("nuxt4-patterns")
    fi
    
    if grep -q '"@nestjs' "$PROJECT_DIR/package.json" 2>/dev/null; then
        SKILLS_NEEDED+=("nestjs-patterns")
    fi
    
    if grep -q '"next' "$PROJECT_DIR/package.json" 2>/dev/null; then
        SKILLS_NEEDED+=("nextjs-turbopack")
        SKILLS_NEEDED+=("frontend-patterns")
    fi
    
    if grep -q '"vite"' "$PROJECT_DIR/package.json" 2>/dev/null; then
        SKILLS_NEEDED+=("vite-patterns")
    fi
    
    if [ -f "$PROJECT_DIR/prisma/schema.prisma" ]; then
        SKILLS_NEEDED+=("prisma-patterns")
    fi
fi

if [ "$(detect_file "requirements.txt")" = "yes" ] || [ "$(detect_file "pyproject.toml")" = "yes" ]; then
    LANGUAGES+=("Python")
    SKILLS_NEEDED+=("python-patterns")
    SKILLS_NEEDED+=("python-testing")
    
    if grep -qi "fastapi" "$PROJECT_DIR/requirements.txt" "$PROJECT_DIR/pyproject.toml" 2>/dev/null; then
        SKILLS_NEEDED+=("fastapi-patterns")
    fi
    if grep -qi "django" "$PROJECT_DIR/requirements.txt" "$PROJECT_DIR/pyproject.toml" 2>/dev/null; then
        SKILLS_NEEDED+=("django-patterns")
        SKILLS_NEEDED+=("django-security")
    fi
fi

if [ "$(detect_file "go.mod")" = "yes" ]; then
    LANGUAGES+=("Go")
    SKILLS_NEEDED+=("golang-patterns")
    SKILLS_NEEDED+=("golang-testing")
fi

if [ "$(detect_file "Cargo.toml")" = "yes" ]; then
    LANGUAGES+=("Rust")
    SKILLS_NEEDED+=("rust-patterns")
    SKILLS_NEEDED+=("rust-testing")
fi

if [ "$(detect_file "pom.xml")" = "yes" ] || [ "$(detect_file "build.gradle")" = "yes" ]; then
    LANGUAGES+=("Java")
    SKILLS_NEEDED+=("springboot-patterns")
    SKILLS_NEEDED+=("java-coding-standards")
fi

if [ "$(detect_file "CMakeLists.txt")" = "yes" ]; then
    LANGUAGES+=("C++")
    SKILLS_NEEDED+=("cpp-coding-standards")
    SKILLS_NEEDED+=("cpp-testing")
fi

if [ -d "$PROJECT_DIR/android" ] || [ -f "$PROJECT_DIR/settings.gradle.kts" ]; then
    LANGUAGES+=("Kotlin")
    SKILLS_NEEDED+=("kotlin-patterns")
    SKILLS_NEEDED+=("kotlin-testing")
fi

if [ -d "$PROJECT_DIR/ios" ] || [ -f "$PROJECT_DIR/*.xcodeproj" ] 2>/dev/null; then
    LANGUAGES+=("Swift")
    SKILLS_NEEDED+=("swiftui-patterns")
fi

# Always include core skills
SKILLS_NEEDED+=("coding-standards")
SKILLS_NEEDED+=("security-review")
SKILLS_NEEDED+=("error-handling")

# Check for Docker
if [ -f "$PROJECT_DIR/Dockerfile" ] || [ -f "$PROJECT_DIR/docker-compose.yml" ]; then
    SKILLS_NEEDED+=("docker-patterns")
fi

# Check for database
if [ -f "$PROJECT_DIR/prisma/schema.prisma" ]; then
    SKILLS_NEEDED+=("postgres-patterns")
fi

# Remove duplicates
SKILLS_NEEDED=($(echo "${SKILLS_NEEDED[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

# --- Generate Output ---
cat > "$OUTPUT_FILE" << EOF
# Auto-detected Project Context
## Project: $(basename "$PROJECT_DIR")

**Detected Languages:** ${LANGUAGES[*]:-Unknown}
**Recommended Skills:**
EOF

for skill in "${SKILLS_NEEDED[@]}"; do
    echo "- \`$skill\`" >> "$OUTPUT_FILE"
done

cat >> "$OUTPUT_FILE" << EOF

## Loading Context
This file was auto-generated by ECC Project Detector.
EOF

echo "========================================="
echo "📋 Project: $(basename "$PROJECT_DIR")"
echo "🌐 Languages: ${LANGUAGES[*]:-Unknown}"
echo "🎯 Skills matched: ${#SKILLS_NEEDED[@]}"
echo "========================================="
echo ""
echo "SKILLS_TO_LOAD:"
printf '  - skill("%s")\n' "${SKILLS_NEEDED[@]}"
echo ""
echo "=== RUN: usa el tool 'skill' para cargar cada una ==="
echo "Output file: $OUTPUT_FILE"
